name: CSharp CI

on:
 push:
   branches:
   - trunk

jobs:
  build:
    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '8.0.x'
    - name: Run unit checks
      run: dotnet test Timesheet.Tests --filter FullyQualifiedName~Timesheet.Tests.Unit
    - name: Run app
      run: |
        cd Timesheet
        dotnet build
        cd ../Timesheet.Tests
        dotnet build
        cd ../Timesheet
        dotnet run --project Timesheet.csproj &
    
    - name: Wait for app to start
      run: sleep 10 # Wait for the app to start and the database to be created
    
    - name: Install Selenium WebDriver
      run: |
        cd Timesheet.Tests
        dotnet add package Selenium.WebDriver
        dotnet add package Selenium.WebDriver.ChromeDriver
        dotnet add package WebDriverManager
        dotnet add package NUnit
        dotnet add package NUnit3TestAdapter
        dotnet add package Allure.NUnit
    
    #- name: Setup ChromeDriver
     # run: WebDriverManager.Net.exe --browser-version auto
    
    - name: Run E2E tests
      run: |
        dotnet test Timesheet.Tests --filter Timesheet.Tests.API --no-build